brands/urls.py
from . import views
from django.urls import path


app_name = 'brands'

urlpatterns = [
    path('create/', views.create_brand, name='create')
]

catalogs/urls.py
from django.urls import path
from . import views


app_name = 'catalogs'

urlpatterns = [
    path('create/', views.create_category, name='create'),
]

colors/urls.py
from django.urls import path
from . import views


app_name = 'colors'

urlpatterns = [
    path('create/', views.create_color, name='create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('brands/', include('brands.urls')),
    path('colors/', include('colors.urls')),
    path('catalogs/', include('catalogs.urls')),
    path('products/', include('products.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('create/', views.create_product, name='create'),
    path('detail/<int:year>/<int:month>/<int:day>/<slug:slug>/', views.product_detail, name='detail'),
    path('category/<slug:category>/', views.product_by_category, name='category'),
    path('list/', views.product_by_category, name='list'),
]

templates/includes/footer.html
<footer class="animate-fade-in">
    <p>&copy; 2023 Astrum Market. All rights reserved.</p>
</footer>

templates/includes/header.html
<header class="animate-fade-in">
    <div class="header-content">
        <a href="/" class="logo">Astrum Market</a>
        <nav>
            <a href="{% url 'home' %}">Home</a>
            <a href="{% if category.slug %}{% url 'products:category' category.slug %}{% else %}{% url 'products:list' %}{% endif %}">Products</a>
            <a href="{% url 'products:create' %}">Add Product</a>
            <a href="{% url 'brands:create' %}">Add Brand</a>
            <a href="{% url 'catalogs:create' %}">Add Category</a>
            <a href="{% url 'colors:create' %}">Add Color</a>
        </nav>
    </div>
</header>